"""GENERATED by protocol/generate.py from protocol.toml — DO NOT EDIT."""

from enum import IntEnum

PROTO_VERSION = 1
CAPS = frozenset(['capture', 'markers', 'verbs'])

class Txn(IntEnum):
    INFO = 0x01  # Device info + capability gate (QIC bit + proto version)
    SET_TIMING = 0x02  # Set QIC pulse/report cadence (idle-only)
    SELECT = 0x03  # Drive-select hint (idle-only; sticky-select optional)
    COMMAND_TXN = 0x04  # Emit n STEP pulses verbatim; optionally clock report_bits off TRK0
    WAIT_READY = 0x05  # Poll the ready/INDEX line until ready or timeout
    CAPTURE = 0x06  # Open a free-running flux capture session (device holds the lease)
    ABORT = 0x07  # Out-of-band stop valid during CAPTURE; routes through Quiesce


class Marker(IntEnum):
    SESSION_START = 0xF0  # rate, sample clock, TPT, direction, pass-id, UTC — anchors t=0
    SEGMENT = 0xF1  # tick count since previous + running index — each hardware INDEX edge
    EVENT = 0xF2  # code: motion-started / hole-EOT / overflow / gap
    END = 0xF3  # reason, flux-count, byte-count, checksum — seals the run
    HEARTBEAT = 0xF4  # coarse keepalive across long erased stretches (demoted, optional)


class Event(IntEnum):
    MOTION_STARTED = 0x01
    HOLE_EOT = 0x02
    OVERFLOW = 0x03
    GAP = 0x04


class EndReason(IntEnum):
    NORMAL = 0x00
    ABORT = 0x01
    OVERFLOW = 0x02
    EOT = 0x03
    USB_LOSS = 0x04
    WATCHDOG = 0x05
