"""Hatchling build hook: stamp the git commit into the wheel (for ``tw info``).

Writes ``tapewyrm/_build_stamp.py`` into the *wheel only* (via force_include
from a temp file), so the source tree never gets a generated file to ignore.
Skipped for editable installs: those run from the checkout, where
``tapewyrm.buildinfo`` asks git directly and is never stale.
"""

from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path
from typing import Any

from hatchling.builders.hooks.plugin.interface import BuildHookInterface


def _git(cwd: str, *args: str) -> str | None:
    try:
        out = subprocess.run(["git", *args], cwd=cwd, capture_output=True, text=True, check=True)
    except (OSError, subprocess.CalledProcessError):
        return None
    return out.stdout.strip()


class CustomBuildHook(BuildHookInterface):
    def initialize(self, version: str, build_data: dict[str, Any]) -> None:
        if version == "editable":
            return
        commit = _git(self.root, "rev-parse", "HEAD") or ""
        dirty = bool(_git(self.root, "status", "--porcelain", "--untracked-files=no", "--", "."))
        stamp = Path(tempfile.mkdtemp()) / "_build_stamp.py"
        stamp.write_text(
            '"""Generated by hatch_build.py at wheel build time -- do not edit."""\n'
            f"COMMIT = {commit!r}\n"
            f"DIRTY = {dirty!r}\n",
            encoding="utf-8",
        )
        build_data["force_include"][str(stamp)] = "tapewyrm/_build_stamp.py"
