# PlatformIO pre-script: per-file compiler flags (the old Rules.mk/Makefile
# target-specific variables).
#
# Why this is a *pre* script: PlatformIO consults build middlewares while it
# collects the project's sources, which happens inside env.BuildProgram() in the
# platform's builder/main.py -- i.e. BEFORE any post: script runs. Middlewares
# registered later are silently ignored.
#
# Why the middlewares only set $TW_FILE_CFLAGS and never touch $CFLAGS
# directly: a middleware's overrides are evaluated *now*, at collection time,
# but scripts/pio_post.py replaces $CFLAGS wholesale *afterwards*. If we wrote
# `CFLAGS=env["CFLAGS"] + [...]` here we would freeze the platform's default
# (wrong) flags into those objects. Instead pio_post.py puts the literal
# token "$TW_FILE_CFLAGS" into $CFLAGS, SCons expands it lazily at command
# time, and the per-file override below supplies its value.

import os
import subprocess

Import("env")  # noqa: F821  (SCons injects Import/env)

fw_major = env.GetProjectOption("custom_fw_major")
fw_minor = env.GetProjectOption("custom_fw_minor")
src_dir = env.subst("$PROJECT_SRC_DIR")
build_dir = env.subst("$BUILD_DIR")


def _git(*args):
    """Run git in the firmware tree; None if git or the repo is unavailable."""
    try:
        out = subprocess.run(
            ["git", *args],
            cwd=env.subst("$PROJECT_DIR"),
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    return out.stdout.strip()


# Firmware build identity for `tw info` (BUILD_INFO verb, qic.c). We write it to
# a generated header in the build dir rather than passing a -D string: string
# defines need shell-proof quoting through SCons, and a header keeps the source
# tree clean. SCons content-signs the header, so an unchanged commit does not
# force a rebuild. "Dirty" means uncommitted changes to tracked files under
# firmware/ or protocol/ -- the only paths that change the image.
_commit = _git("rev-parse", "HEAD") or ""
_status = _git("status", "--porcelain", "--untracked-files=no", "--", ".", "../protocol")
_dirty = 1 if _status else 0
os.makedirs(build_dir, exist_ok=True)
_header = (
    "/* Generated by scripts/pio_pre.py -- do not edit. */\n"
    f'#define TW_GIT_COMMIT "{_commit}"\n'
    f"#define TW_GIT_DIRTY {_dirty}\n"
)
_header_path = os.path.join(build_dir, "tw_git.h")
if not os.path.exists(_header_path) or open(_header_path).read() != _header:
    with open(_header_path, "w") as f:
        f.write(_header)


def _with_file_cflags(*flags):
    """Middleware factory: compile the matched node with extra C flags."""

    def _middleware(env, node):
        return env.Object(node, TW_FILE_CFLAGS=list(flags))

    return _middleware


# src/usb/Makefile: `$(OBJS) $(OBJS-y): CFLAGS += -include $(SRCDIR)/defs.h`
env.AddBuildMiddleware(
    _with_file_cflags("-include", f"{src_dir}/usb/defs.h"), "*/usb/*.c"
)

# src/Makefile: GCC would otherwise "optimise" the loops inside our own
# memset/memcpy into calls to memset/memcpy -- infinite recursion.
env.AddBuildMiddleware(
    _with_file_cflags("-fno-tree-loop-distribute-patterns"), "*/util.c"
)

# src/Makefile: build_info.c bakes the firmware version into GetInfo, and (ours)
# the git commit via the generated tw_git.h in the build dir.
#
# The explicit Depends() matters: SCons finds header dependencies by scanning
# #includes along CPPPATH, but the build dir reaches the compiler only through a
# raw -iquote flag, so SCons never saw build_info.c -> tw_git.h. A new commit
# rewrote the header and build_info.o was NOT rebuilt (caught by `tw info`
# reporting the previous commit). We keep CPPPATH empty on purpose (see
# pio_post.py), so declare the edge by hand.
def _build_info_middleware(env, node):
    obj = env.Object(
        node,
        TW_FILE_CFLAGS=[
            f"-DFW_MAJOR={fw_major}", f"-DFW_MINOR={fw_minor}", "-iquote", build_dir
        ],
    )
    env.Depends(obj, _header_path)
    return obj


env.AddBuildMiddleware(_build_info_middleware, "*/build_info.c")
