#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Generate both ends of the Tapewyrm wire protocol from protocol.toml.

Emits:
  - firmware/protocol.h               (C header: #defines + enums)
  - host/tapewyrm/link/protocol.py    (Python IntEnums + version)

CI runs this then `git diff --exit-code`, mechanically enforcing the no-drift
invariant (DESIGN.md §12.4). Stdlib-only (tomllib) so it needs no extra deps.

Usage:
    python protocol/generate.py            # write both files
    python protocol/generate.py --check    # exit 1 if files are stale
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "protocol" / "protocol.toml"
# The C header lives in the vendored GW firmware include path so the QIC sources
# reach it as <protocol.h> via the build's `-iquote inc`.
H_OUT = ROOT / "firmware" / "inc" / "protocol.h"
PY_OUT = ROOT / "host" / "tapewyrm" / "link" / "protocol.py"

GENERATED_BANNER = "GENERATED by protocol/generate.py from protocol.toml — DO NOT EDIT."


def load_spec() -> dict:
    with SPEC.open("rb") as f:
        return tomllib.load(f)


def _entries(spec: dict, key: str) -> list[tuple[str, int, str]]:
    return [(e["name"], int(e["code"]), e.get("desc", "")) for e in spec.get(key, [])]


def render_h(spec: dict) -> str:
    version = int(spec["version"])
    caps = spec.get("caps", [])
    lines: list[str] = [
        "/* " + GENERATED_BANNER + " */",
        "#ifndef TAPEWYRM_PROTOCOL_H",
        "#define TAPEWYRM_PROTOCOL_H",
        "",
        f"#define TW_PROTO_VERSION {version}",
        "",
        "/* Capability flags advertised by INFO (string set on host side). */",
    ]
    for i, cap in enumerate(caps):
        lines.append(f"#define TW_CAP_{cap.upper()} (1u << {i})")
    lines.append("")

    def block(title: str, key: str, prefix: str) -> None:
        lines.append(f"/* {title} */")
        lines.append("enum {")
        for name, code, desc in _entries(spec, key):
            comment = f"  /* {desc} */" if desc else ""
            lines.append(f"    {prefix}{name} = 0x{code:02X},{comment}")
        lines.append("};")
        lines.append("")

    block("USB transaction opcodes (host -> device)", "transaction", "TW_TXN_")
    block("In-flux-stream tape markers (opcode-escape channel)", "marker", "TW_MARK_")
    block("EVENT sub-codes", "event", "TW_EVT_")
    block("END reason codes", "end_reason", "TW_END_")

    lines.append("#endif /* TAPEWYRM_PROTOCOL_H */")
    return "\n".join(lines) + "\n"


def render_py(spec: dict) -> str:
    version = int(spec["version"])
    caps = spec.get("caps", [])
    lines: list[str] = [
        '"""' + GENERATED_BANNER + '"""',
        "",
        "from enum import IntEnum",
        "",
        f"PROTO_VERSION = {version}",
        f"CAPS = frozenset({sorted(caps)!r})",
        "",
    ]

    def block(clsname: str, key: str) -> None:
        lines.append(f"class {clsname}(IntEnum):")
        entries = _entries(spec, key)
        if not entries:
            lines.append("    pass")
        for name, code, desc in entries:
            comment = f"  # {desc}" if desc else ""
            lines.append(f"    {name} = 0x{code:02X}{comment}")
        lines.append("")
        lines.append("")

    block("Txn", "transaction")
    block("Marker", "marker")
    block("Event", "event")
    block("EndReason", "end_reason")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    check = "--check" in sys.argv
    spec = load_spec()
    outputs = {H_OUT: render_h(spec), PY_OUT: render_py(spec)}

    stale = False
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        existing = path.read_text(encoding="utf-8") if path.exists() else None
        if existing != content:
            stale = True
            if check:
                print(f"STALE: {path.relative_to(ROOT)}")
            else:
                path.write_text(content, encoding="utf-8")
                print(f"wrote {path.relative_to(ROOT)}")

    if check and stale:
        print("protocol artifacts are out of date; run `python protocol/generate.py`")
        return 1
    if not stale:
        print("protocol artifacts up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
