/* GENERATED by protocol/generate.py from protocol.toml — DO NOT EDIT. */
#ifndef TAPEWYRM_PROTOCOL_H
#define TAPEWYRM_PROTOCOL_H

#define TW_PROTO_VERSION 1

/* Capability flags advertised by INFO (string set on host side). */
#define TW_CAP_VERBS (1u << 0)
#define TW_CAP_CAPTURE (1u << 1)
#define TW_CAP_MARKERS (1u << 2)

/* USB transaction opcodes (host -> device) */
enum {
    TW_TXN_INFO = 0x01,  /* Device info + capability gate (QIC bit + proto version) */
    TW_TXN_SET_TIMING = 0x02,  /* Set QIC pulse/report cadence (idle-only) */
    TW_TXN_SELECT = 0x03,  /* Drive-select hint (idle-only; sticky-select optional) */
    TW_TXN_COMMAND_TXN = 0x04,  /* Emit n STEP pulses verbatim; optionally clock report_bits off TRK0 */
    TW_TXN_WAIT_READY = 0x05,  /* Poll the ready/INDEX line until ready or timeout */
    TW_TXN_CAPTURE = 0x06,  /* Open a free-running flux capture session (device holds the lease) */
    TW_TXN_ABORT = 0x07,  /* Out-of-band stop valid during CAPTURE; routes through Quiesce */
};

/* In-flux-stream tape markers (opcode-escape channel) */
enum {
    TW_MARK_SESSION_START = 0xF0,  /* rate, sample clock, TPT, direction, pass-id, UTC — anchors t=0 */
    TW_MARK_SEGMENT = 0xF1,  /* tick count since previous + running index — each hardware INDEX edge */
    TW_MARK_EVENT = 0xF2,  /* code: motion-started / hole-EOT / overflow / gap */
    TW_MARK_END = 0xF3,  /* reason, flux-count, byte-count, checksum — seals the run */
    TW_MARK_HEARTBEAT = 0xF4,  /* coarse keepalive across long erased stretches (demoted, optional) */
};

/* EVENT sub-codes */
enum {
    TW_EVT_MOTION_STARTED = 0x01,
    TW_EVT_HOLE_EOT = 0x02,
    TW_EVT_OVERFLOW = 0x03,
    TW_EVT_GAP = 0x04,
};

/* END reason codes */
enum {
    TW_END_NORMAL = 0x00,
    TW_END_ABORT = 0x01,
    TW_END_OVERFLOW = 0x02,
    TW_END_EOT = 0x03,
    TW_END_USB_LOSS = 0x04,
    TW_END_WATCHDOG = 0x05,
};

#endif /* TAPEWYRM_PROTOCOL_H */
